#:schema node_modules/wrangler/config-schema.json
name = "713sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "137da06bc04642e181b6e8ce8e939ac8" }
]

[assets]
directory = "./public"
